# Generated by Django 5.1.6 on 2025-02-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contacts/', verbose_name='Rasm')),
                ('phone_numbers', models.CharField(blank=True, help_text="Bog'lanish uchun telefon raqami.", max_length=15, null=True, verbose_name='Telefon raqam')),
                ('fax_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Faks raqam')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_uz', models.TextField(blank=True, null=True, verbose_name='Manzil (UZ)')),
                ('address_ru', models.TextField(blank=True, null=True, verbose_name='Manzil (RU)')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='Manzil (EN)')),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontaktlar',
            },
        ),
    ]
