# Generated by Django 5.1.6 on 2025-03-01 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Maqola muallifi (UZ)')),
            ],
            options={
                'verbose_name': 'Maqola muallifi',
                'verbose_name_plural': 'Maqola mualliflari',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('description', models.TextField(verbose_name='Konferensiya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Konferensiya',
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Jurnal nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Jurnal nomi (RU)')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Jurnal nomi (EN)')),
                ('cover_image', models.ImageField(upload_to='bosh_sahifa/jurnal/jurnal_rasmi', verbose_name='Jurnal old muqovasi rasmi')),
                ('image_2', models.ImageField(upload_to='bosh_sahifa/jurnal/jurnal_rasmi', verbose_name='Jurnal orqa muqovasi rasmi')),
                ('which_number', models.CharField(help_text='Namuna: 1-son | 01.2025', max_length=50, verbose_name='Jurnal soni')),
                ('slug', models.SlugField(help_text='Namuna: 1-son-01-2025-yil', unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('upload_file_uz', models.FileField(blank=True, null=True, upload_to='bosh_sahifa/jurnal/uz', verbose_name='Jurnal faylini yuklash (UZ)')),
                ('upload_file_ru', models.FileField(blank=True, null=True, upload_to='bosh_sahifa/jurnal/ru', verbose_name='Jurnal faylini yuklash (RU)')),
                ('upload_file_en', models.FileField(blank=True, null=True, upload_to='bosh_sahifa/jurnal/en', verbose_name='Jurnal faylini yuklash (RU)')),
            ],
            options={
                'verbose_name': 'Jurnal',
                'verbose_name_plural': 'Jurnallar',
            },
        ),
        migrations.CreateModel(
            name='ArticleCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Kategoriya nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kategoriya nomi (RU)')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Kategoriya nomi (EN)')),
                ('magazine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='bosh_sahifa.magazine', verbose_name='Jurnal soni')),
            ],
            options={
                'verbose_name': 'Maqola kategoriyasi',
                'verbose_name_plural': 'Maqola kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=200, verbose_name='Maqola nomi (UZ)')),
                ('name_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Maqola nomi (RU)')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Maqola nomi (EN)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('upload_file_uz', models.FileField(blank=True, null=True, upload_to='bosh_sahifa/maqolalar/uz', verbose_name='Maqola fayli (UZ)')),
                ('upload_file_ru', models.FileField(blank=True, null=True, upload_to='bosh_sahifa/maqolalar/ru', verbose_name='Maqola fayli (RU)')),
                ('upload_file_en', models.FileField(blank=True, null=True, upload_to='bosh_sahifa/maqolalar/en', verbose_name='Maqola fayli (EN)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='bosh_sahifa.articleauthor', verbose_name='Muallifi')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bosh_sahifa.articlecategories', verbose_name='Kategoriya')),
                ('magazine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='bosh_sahifa.magazine', verbose_name='Jurnali')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
    ]
