# Generated by Django 5.1.6 on 2025-02-20 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosh_sahifa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategories',
            name='magazine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kategoriya', to='bosh_sahifa.magazine', verbose_name='Jurnal_soni'),
        ),
    ]
