# Generated by Django 5.1.6 on 2025-02-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosh_sahifa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='upload_file',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='upload_file',
        ),
        migrations.AddField(
            model_name='article',
            name='upload_file_en',
            field=models.FileField(blank=True, null=True, upload_to='bosh_sahifa/maqolalar/en', verbose_name='Maqola fayli (EN)'),
        ),
        migrations.AddField(
            model_name='article',
            name='upload_file_ru',
            field=models.FileField(blank=True, null=True, upload_to='bosh_sahifa/maqolalar/ru', verbose_name='Maqola fayli (RU)'),
        ),
        migrations.AddField(
            model_name='article',
            name='upload_file_uz',
            field=models.FileField(blank=True, null=True, upload_to='bosh_sahifa/maqolalar/uz', verbose_name='Maqola fayli (UZ)'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='upload_file_en',
            field=models.FileField(blank=True, null=True, upload_to='bosh_sahifa/jurnal/en', verbose_name='Jurnal faylini yuklash (RU)'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='upload_file_ru',
            field=models.FileField(blank=True, null=True, upload_to='bosh_sahifa/jurnal/ru', verbose_name='Jurnal faylini yuklash (RU)'),
        ),
        migrations.AddField(
            model_name='magazine',
            name='upload_file_uz',
            field=models.FileField(blank=True, null=True, upload_to='bosh_sahifa/jurnal/uz', verbose_name='Jurnal faylini yuklash (UZ)'),
        ),
    ]
