# Generated by Django 5.1.6 on 2025-02-20 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosh_sahifa', '0002_articlecategories_magazine'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='magazine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='bosh_sahifa.magazine', verbose_name='Jurnali'),
        ),
    ]
