# Generated by Django 5.1.6 on 2025-02-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosh_sahifa', '0003_article_magazine'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
    ]
