# Generated by Django 5.1.5 on 2025-01-29 13:49

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bosh_sahifa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Arxiv')),
            ],
            options={
                'verbose_name': 'Arxiv',
                'verbose_name_plural': 'Jurnal arxivlari',
            },
        ),
        migrations.CreateModel(
            name='MagazineRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Masalan: 'Jurnal nomi' elektron jurnalida maqola chop ettirish talablari", max_length=200, verbose_name='jurnal talablari nomi')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name="Jurnal talablari to'liq")),
            ],
            options={
                'verbose_name': 'Jurnal talablari',
                'verbose_name_plural': 'Jurnal talablari',
            },
        ),
        migrations.CreateModel(
            name='AboutMagazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Jurnal haqida')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosh_sahifa.magazine', verbose_name='Jurnal nomi')),
            ],
            options={
                'verbose_name': 'Jurnal haqida',
                'verbose_name_plural': 'Jurnal haqida',
            },
        ),
        migrations.CreateModel(
            name='MagazineNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='yangilik nomi')),
                ('content', models.TextField(verbose_name='Yangilik haqida')),
                ('image', models.ImageField(blank=True, null=True, upload_to='jurnal/news', verbose_name='rasm')),
                ('link', models.URLField(blank=True, null=True, verbose_name='havola')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosh_sahifa.magazine', verbose_name='Jurnal nomi')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Jurnal yangiliklari',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Statistika kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Statistika yangilangan sana')),
                ('magazine', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='bosh_sahifa.magazine', verbose_name='Jurnal')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
            },
        ),
    ]
