# Generated by Django 5.1.6 on 2025-02-20 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bosh_sahifa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_uz', models.TextField(verbose_name='Arxiv (UZ)')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name='Arxiv (RU)')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='Arxiv (EN)')),
            ],
            options={
                'verbose_name': 'Arxiv',
                'verbose_name_plural': 'Jurnal arxivlari',
            },
        ),
        migrations.CreateModel(
            name='MagazineRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Jurnal talablari nomi (UZ)')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Jurnal talablari nomi (RU)')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Jurnal talablari nomi (EN)')),
                ('content_uz', models.TextField(blank=True, null=True, verbose_name="Jurnal talablari to'liq (UZ)")),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name="Jurnal talablari to'liq (RU)")),
                ('content_en', models.TextField(blank=True, null=True, verbose_name="Jurnal talablari to'liq (EN)")),
            ],
            options={
                'verbose_name': 'Jurnal talablari',
                'verbose_name_plural': 'Jurnal talablari',
            },
        ),
        migrations.CreateModel(
            name='AboutMagazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_uz', models.TextField(verbose_name='Jurnal haqida (UZ)')),
                ('bio_ru', models.TextField(blank=True, null=True, verbose_name='Jurnal haqida (RU)')),
                ('bio_en', models.TextField(blank=True, null=True, verbose_name='Jurnal haqida (EN)')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosh_sahifa.magazine', verbose_name='Jurnal nomi')),
            ],
            options={
                'verbose_name': 'Jurnal haqida',
                'verbose_name_plural': 'Jurnal haqida',
            },
        ),
        migrations.CreateModel(
            name='MagazineNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=500, verbose_name='Yangilik nomi (UZ)')),
                ('title_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='Yangilik nomi (RU)')),
                ('title_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Yangilik nomi (EN)')),
                ('content_uz', models.TextField(verbose_name='Yangilik haqida (UZ)')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name='Yangilik haqida (RU)')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='Yangilik haqida (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='jurnal/news', verbose_name='Rasm')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Havola')),
                ('magazine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosh_sahifa.magazine', verbose_name='Jurnal nomi')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Jurnal yangiliklari',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Statistika kiritilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Statistika yangilangan sana')),
                ('magazine', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='bosh_sahifa.magazine', verbose_name='Jurnal')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
            },
        ),
    ]
