# Generated by Django 5.1.6 on 2025-03-01 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosh_sahifa', '0001_initial'),
        ('jurnal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmagazine',
            options={'verbose_name': 'Jurnal haqida', 'verbose_name_plural': 'Jurnal haqida'},
        ),
        migrations.RemoveField(
            model_name='aboutmagazine',
            name='file_en',
        ),
        migrations.RemoveField(
            model_name='aboutmagazine',
            name='file_ru',
        ),
        migrations.RemoveField(
            model_name='aboutmagazine',
            name='file_uz',
        ),
        migrations.AddField(
            model_name='aboutmagazine',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='jurnal_haqida_fayl/', verbose_name='fayl'),
        ),
        migrations.AddField(
            model_name='aboutmagazine',
            name='magazine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bosh_sahifa.magazine', verbose_name='Jurnal nomi'),
        ),
    ]
