# Generated by Django 5.1.6 on 2025-02-25 16:15

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmagazine',
            name='bio_en',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Jurnal haqida (EN)'),
        ),
        migrations.AlterField(
            model_name='aboutmagazine',
            name='bio_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Jurnal haqida (RU)'),
        ),
        migrations.AlterField(
            model_name='aboutmagazine',
            name='bio_uz',
            field=tinymce.models.HTMLField(verbose_name='Jurnal haqida (UZ)'),
        ),
    ]
