# Generated by Django 5.1.6 on 2025-03-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0001_initial'),
    ]

    operations = [
    ]
