# Generated by Django 5.1.6 on 2025-02-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0002_alter_aboutmagazine_bio_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmagazine',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='Jurnal haqida (EN)'),
        ),
        migrations.AlterField(
            model_name='aboutmagazine',
            name='bio_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Jurnal haqida (RU)'),
        ),
        migrations.AlterField(
            model_name='aboutmagazine',
            name='bio_uz',
            field=models.TextField(verbose_name='Jurnal haqida (UZ)'),
        ),
    ]
