# Generated by Django 5.1.6 on 2025-03-01 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0002_rename_name_aboutmagazine_name_uz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmagazine',
            old_name='name_uz',
            new_name='magazine',
        ),
    ]
