# Generated by Django 5.1.6 on 2025-03-01 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosh_sahifa', '0001_initial'),
        ('jurnal', '0003_rename_name_uz_aboutmagazine_magazine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmagazine',
            name='magazine',
        ),
        migrations.AddField(
            model_name='aboutmagazine',
            name='name_uz',
            field=models.ForeignKey(default='default_journal', on_delete=django.db.models.deletion.CASCADE, related_name='about_magazine', to='bosh_sahifa.magazine', verbose_name='Jurnal nomi'),
            preserve_default=False,
        ),
    ]
