# Generated by Django 5.1.6 on 2025-03-02 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosh_sahifa', '0001_initial'),
        ('jurnal', '0003_rename_file_aboutmagazine_file_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmagazine',
            name='magazine_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Jurnal nomi (EN)'),
        ),
        migrations.AddField(
            model_name='aboutmagazine',
            name='magazine_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Jurnal nomi (RU)'),
        ),
        migrations.AddField(
            model_name='aboutmagazine',
            name='magazine_name_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Jurnal nomi (UZ)'),
        ),
        migrations.AlterField(
            model_name='aboutmagazine',
            name='file_uz',
            field=models.FileField(blank=True, null=True, upload_to='jurnal_haqida_fayl/', verbose_name='Fayl (UZ)'),
        ),
        migrations.AlterField(
            model_name='aboutmagazine',
            name='magazine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bosh_sahifa.magazine', verbose_name='Jurnal'),
        ),
    ]
