# Generated by Django 5.1.6 on 2025-02-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0003_alter_aboutmagazine_bio_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmagazine',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='jurnal_haqida_fayl/', verbose_name='fayl'),
        ),
    ]
