# Generated by Django 5.1.6 on 2025-03-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal', '0005_alter_aboutmagazine_magazine_name_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutmagazine',
            old_name='magazine_name_en',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='aboutmagazine',
            old_name='magazine_name_ru',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='aboutmagazine',
            old_name='magazine_name_uz',
            new_name='name_uz',
        ),
    ]
