# Generated by Django 5.1.5 on 2025-02-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePreparationGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='Yuriqnoma/articles/', verbose_name="Yo'riqnoma fayli")),
            ],
            options={
                'verbose_name': "Maqola yo'riqnomasi",
                'verbose_name_plural': "Maqolalar yo'riqnomasi",
            },
        ),
        migrations.CreateModel(
            name='CopyRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=200, verbose_name='Mualliflik huquqi nomi (UZ)')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Mualliflik huquqi nomi (RU)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Mualliflik huquqi nomi (EN)')),
                ('content_uz', models.TextField(verbose_name='Mualliflik huquqi matni (UZ)')),
                ('content_ru', models.TextField(verbose_name='Mualliflik huquqi matni (RU)')),
                ('content_en', models.TextField(verbose_name='Mualliflik huquqi matni (EN)')),
            ],
            options={
                'verbose_name': 'Mualliflik huquqi',
                'verbose_name_plural': 'Mualliflik huquqlari',
            },
        ),
        migrations.CreateModel(
            name='SampleDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Namunaviy hujjat nomi (UZ)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Namunaviy hujjat nomi (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Namunaviy hujjat nomi (EN)')),
                ('content_uz', models.TextField(verbose_name='Hujjat matni (UZ)')),
                ('content_ru', models.TextField(verbose_name='Hujjat matni (RU)')),
                ('content_en', models.TextField(verbose_name='Hujjat matni (EN)')),
            ],
            options={
                'verbose_name': 'Namunaviy hujjat',
                'verbose_name_plural': 'Namunaviy hujjatlar',
            },
        ),
    ]
