# Generated by Django 5.1.6 on 2025-02-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mualliflarga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepreparationguide',
            name='upload_file',
        ),
        migrations.AddField(
            model_name='articlepreparationguide',
            name='upload_file_en',
            field=models.FileField(blank=True, null=True, upload_to='Yuriqnoma/articles/en/', verbose_name="Yo'riqnoma fayli (EN)"),
        ),
        migrations.AddField(
            model_name='articlepreparationguide',
            name='upload_file_ru',
            field=models.FileField(blank=True, null=True, upload_to='Yuriqnoma/articles/ru/', verbose_name="Yo'riqnoma fayli (RU)"),
        ),
        migrations.AddField(
            model_name='articlepreparationguide',
            name='upload_file_uz',
            field=models.FileField(blank=True, null=True, upload_to='Yuriqnoma/articles/uz/', verbose_name="Yo'riqnoma fayli (UZ)"),
        ),
    ]
