# Generated by Django 5.1.6 on 2025-02-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mualliflarga', '0002_remove_articlepreparationguide_upload_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepreparationguide',
            name='upload_file_en',
        ),
        migrations.RemoveField(
            model_name='articlepreparationguide',
            name='upload_file_ru',
        ),
        migrations.RemoveField(
            model_name='articlepreparationguide',
            name='upload_file_uz',
        ),
        migrations.AddField(
            model_name='articlepreparationguide',
            name='yuriqnoma_en',
            field=models.TextField(blank=True, null=True, verbose_name="Yo'riqnoma (EN)"),
        ),
        migrations.AddField(
            model_name='articlepreparationguide',
            name='yuriqnoma_ru',
            field=models.TextField(blank=True, null=True, verbose_name="Yo'riqnoma (RU)"),
        ),
        migrations.AddField(
            model_name='articlepreparationguide',
            name='yuriqnoma_uz',
            field=models.TextField(blank=True, null=True, verbose_name="Yo'riqnoma (UZ)"),
        ),
    ]
