# Generated by Django 5.1.6 on 2025-02-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IlmiyMaktablarim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name="To'liq ism familiya")),
                ('academic_degree_uz', models.CharField(blank=True, help_text='Masalan: Iqtisodiyot fanlari doktori, akademik', max_length=200, null=True, verbose_name='Ilmiy daraja (UZ)')),
                ('academic_degree_ru', models.CharField(blank=True, help_text='Например: Доктор экономических наук, академик', max_length=200, null=True, verbose_name='Ilmiy daraja (RU)')),
                ('academic_degree_en', models.CharField(blank=True, help_text='For example: Doctor of Economic Sciences, academician', max_length=200, null=True, verbose_name='Ilmiy daraja (EN)')),
                ('haqida_uz', models.TextField(blank=True, null=True, verbose_name='Haqida (UZ)')),
                ('haqida_ru', models.TextField(blank=True, null=True, verbose_name='Haqida (RU)')),
                ('haqida_en', models.TextField(blank=True, null=True, verbose_name='Haqida (EN)')),
            ],
            options={
                'verbose_name': 'Ilmiy maktab',
                'verbose_name_plural': 'Ilmiy maktablarim',
            },
        ),
    ]
