# Generated by Django 5.1.5 on 2025-02-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IlmiyMaktablarim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name="To'liq ism familiya")),
                ('academic_degree', models.CharField(blank=True, help_text='Masalan: Iqtisodiyot fanlari doktori, akademik', max_length=200, null=True, verbose_name='ilmiy daraja')),
                ('haqida', models.TextField(blank=True, null=True, verbose_name='haqida')),
            ],
            options={
                'verbose_name': 'Ilmiy maktab',
                'verbose_name_plural': 'Ilmiy maktablarim',
            },
        ),
    ]
