# Generated by Django 5.1.5 on 2025-01-24 16:39

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IlmiyMaktablarim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='ilmiy_maktablarimiz/')),
                ('academic_degree', models.CharField(max_length=200)),
                ('bio', django_ckeditor_5.fields.CKEditor5Field()),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
    ]
