# Generated by Django 5.1.6 on 2025-02-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name="To'liq ism-familiyasi")),
                ('title_1_uz', models.CharField(blank=True, help_text='Majburiy emas', max_length=255, null=True, verbose_name='Rahbariyat haqida (UZ)')),
                ('title_1_ru', models.CharField(blank=True, help_text='Majburiy emas', max_length=255, null=True, verbose_name='Rahbariyat haqida (RU)')),
                ('title_1_en', models.CharField(blank=True, help_text='Majburiy emas', max_length=255, null=True, verbose_name='Rahbariyat haqida (EN)')),
                ('title_2_uz', models.CharField(blank=True, help_text='Majburiy emas', max_length=255, null=True, verbose_name="Qo'shimcha ma'lumot (UZ)")),
                ('title_2_ru', models.CharField(blank=True, help_text='Majburiy emas', max_length=255, null=True, verbose_name="Qo'shimcha ma'lumot (RU)")),
                ('title_2_en', models.CharField(blank=True, help_text='Majburiy emas', max_length=255, null=True, verbose_name="Qo'shimcha ma'lumot (EN)")),
                ('image', models.ImageField(upload_to='tahririyat/tahririyat_rahbaryati/', verbose_name='Rasmi')),
            ],
            options={
                'verbose_name': 'Tahririyat Rahbaryati',
                'verbose_name_plural': 'Tahririyat Rahbaryati',
            },
        ),
        migrations.CreateModel(
            name='EditorialStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name="Tahririyat a'zolari ro'yxati (UZ)")),
            ],
            options={
                'verbose_name': 'Tahririyat A’zolari',
                'verbose_name_plural': 'Tahririyat A’zolari',
            },
        ),
        migrations.CreateModel(
            name='ForeignEditorialMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism-familiyasi')),
                ('image', models.ImageField(upload_to='tahririyat/xorijiy_tahririyat_azolari/', verbose_name='Rasmi')),
                ('position_uz', models.CharField(max_length=255, verbose_name='Lavozimi (UZ)')),
                ('position_ru', models.CharField(max_length=255, verbose_name='Lavozimi (RU)')),
                ('position_en', models.CharField(max_length=255, verbose_name='Lavozimi (EN)')),
                ('university_graduated_uz', models.CharField(max_length=255, verbose_name='Ilmiy darajasi (UZ)')),
                ('university_graduated_ru', models.CharField(max_length=255, verbose_name='Ilmiy darajasi (RU)')),
                ('university_graduated_en', models.CharField(max_length=255, verbose_name='Ilmiy darajasi (EN)')),
            ],
            options={
                'verbose_name': 'Xorijiy Tahririyat A’zolari',
                'verbose_name_plural': 'Xorijiy Tahririyat A’zolari',
            },
        ),
        migrations.CreateModel(
            name='HonoraryForeignEditorialMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism-familiyasi')),
                ('image', models.ImageField(upload_to='tahririyat/fahriy_xorijiy_azolari/', verbose_name='Rasmi')),
                ('position_uz', models.CharField(max_length=255, verbose_name='Lavozimi (UZ)')),
                ('position_ru', models.CharField(max_length=255, verbose_name='Lavozimi (RU)')),
                ('position_en', models.CharField(max_length=255, verbose_name='Lavozimi (EN)')),
            ],
            options={
                'verbose_name': 'Fahriy Xorijiy A’zolari',
                'verbose_name_plural': 'Fahriy Xorijiy A’zolari',
            },
        ),
    ]
