# Generated by Django 5.1.5 on 2025-01-26 11:19

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name="To'liq ism-familiyasi")),
                ('title_1', models.CharField(blank=True, help_text='Majburiy emas', max_length=255, null=True, verbose_name='rahbariyat haqida')),
                ('title_2', models.CharField(blank=True, help_text='Majnuriy emas', max_length=255, null=True, verbose_name='rahbariyat haqida')),
                ('image', models.ImageField(upload_to='tahririyat/tahririyat_rahbaryati/', verbose_name='rasmi')),
            ],
            options={
                'verbose_name': 'Tahririyat Rahbaryati',
                'verbose_name_plural': 'Tahririyat Rahbaryati',
            },
        ),
        migrations.CreateModel(
            name='EditorialStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name="Tahririyat a'zolari ro'yxati")),
            ],
            options={
                'verbose_name': 'Tahririyat Azolari',
                'verbose_name_plural': 'Tahririyat Azolari',
            },
        ),
        migrations.CreateModel(
            name='ForeignEditorialMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism-familiyasi')),
                ('image', models.ImageField(upload_to='tahririyat/xorijiy_tahririyat_azolari/', verbose_name='rasmi')),
                ('position', models.CharField(max_length=255, verbose_name='lvozimi')),
                ('university_graduated', models.CharField(max_length=255, verbose_name='ilmiy darajasi')),
            ],
            options={
                'verbose_name': 'Xorijiy Tahririyat Azolari',
                'verbose_name_plural': 'Xorijiy Tahririyat Azolari',
            },
        ),
        migrations.CreateModel(
            name='HonoraryForeignEditorialMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ism-familiyasi')),
                ('image', models.ImageField(upload_to='tahririyat/fahriy_xorijiy_azolari/', verbose_name='rasmi')),
                ('position', models.CharField(max_length=255, verbose_name='lavozimi')),
            ],
            options={
                'verbose_name': 'Fahriy Xorijiy Azolari',
                'verbose_name_plural': 'Fahriy Xorijiy Azolari',
            },
        ),
    ]
